/*
 * This source file was generated by the Gradle 'init' task
 */
package dependency.injection;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void contextTest() {
        Context context = new BasicContext();
        context.addBean(User.class);
        User user = context.getBean(User.class);
        assertNotNull(user);
    }
}

class User {
}