/*
 * This source file was generated by the Gradle 'init' task
 */
package dependency.injection;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.List;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void ATest() {
        Context context = new BasicContext();
        context.addBean(A.class);
        A user = context.getBean(A.class);
        assertNotNull(user);
    }

    @Test void BTest() {
        Context context = new BasicContext();
        context.addBean(A.class);
        context.addBean(B.class);
        B b = context.getBean(B.class);
        assertNotNull(b);
        A a = b.getA();
        assertNotNull(a);
    }

    @Test void greetingTest() {
        Context context =new BasicContext();
        context.addBean(A.class);
        context.addBean(B.class);
        List<Greeting> greetings = context.getBeans(Greeting.class);
        assertEquals(2, greetings.size());
    }
}

interface Greeting {
    void greeting();
}

class A implements Greeting {

    @Override
    public void greeting() {
        System.out.println("greeting from A");
    }
}

class B implements Greeting {
    public B(A a) {
        this.a = a;
    }

    public A getA() {
        return this.a;
    }

    private A a;

    @Override
    public void greeting() {
        System.out.println("greeting from B");
    }
}