/*
 * This source file was generated by the Gradle 'init' task
 */
package dependency.injection;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.util.Map;

import org.junit.jupiter.api.Test;

import dependency.injection.context.BasicContext;
import dependency.injection.context.Context;

class AppTest {
    @Test void ATest() {
        try (Context context = new BasicContext()) {
            context.register(A.class);
            A user = context.getBean(A.class);
            assertNotNull(user);
        }
    }

    @Test void BTest() {
        try (Context context = new BasicContext()) {
            context.register(A.class);
            context.register(B.class);
            B b = context.getBean(B.class);
            assertNotNull(b);
            A a = b.getA();
            assertNotNull(a);
        }
    }

    @Test void greetingTest() {
        try (Context context = new BasicContext()) {
            context.register(A.class);
            context.register(B.class);
            Map<String, Greeting> greetings = context.getBeansOfType(Greeting.class);
            assertEquals(2, greetings.size());
        }
    }
}

interface Greeting {
    void greeting();
}

class A implements Greeting {

    @Override
    public void greeting() {
        System.out.println("greeting from A");
    }
}

class B implements Greeting {
    public B(A a) {
        this.a = a;
    }

    public A getA() {
        return this.a;
    }

    private A a;

    @Override
    public void greeting() {
        System.out.println("greeting from B");
    }
}